### ISSUE TITLE
Choose a primary colour for the design

### ISSUE THREAD

**Issue by keithamoss** [keithamoss/mapa#41]
https://m3.material.io/styles/color/dynamic-color/overview
https://github.com/mui/material-ui/issues/29345 (there's an example here of hacky dynamic colour into the current MUI)

**Comment by keithamoss** [comment]
@helenensikat Perhaps your shade of green?

**Comment by helenensikat** [comment]
I'm thinking one that's close to it but a little more saturated.
What about #699222 as the main colour, and #226992 and #922269 for secondary highlights/contrasting touches?  Here's a palette with black and white as well: [Adobe Color](https://color.adobe.com/Mapa-color-theme-b3bb1170-a1b2-49b0-adff-15b7bbf12c88)

**Comment by keithamoss** [comment]
First pass:

The "Set Defaults" button is using #226992 and the other two are using #922269.

Haven't touched headings/sections yet, they're still using #699222.

![Screenshot 2023-05-20 at 17 39 03](https://github.com/keithamoss/mapa/assets/1672960/f1273ca8-19c6-4d94-ae46-da63f6a5edb0)

**Comment by helenensikat** [comment]
Happy to close this one out if you've got no issues with the palette, and we can have a review of styling/CSS/design in person.
