### ISSUE TITLE
Set up project documenation space

### ISSUE THREAD

**Issue by helenensikat** [keithamoss/mapa#62]
@keithamoss 

Dependency: Agreement on what to use for documentation (github wiki, github pages, gitbook integration, other?).

**Comment by keithamoss** [comment]
GitHub Wiki works for now, I think?

I expect we'd eventually transition the help doco into the app itself, so it may be somewhat short lived.

I've sent you an invite to collaborate on the repo - that'll let you start populating the Wiki.

**Comment by helenensikat** [comment]
Thanks, good plan!
